version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    volumes:
      - .:/demo-app-web
    working_dir: /demo-app-web
    command: /bin/bash -c "dotnet restore --packages ./packages ./DemoApp.sln && dotnet publish -r debian.8-x64 ./src/DemoApp.Web/DemoApp.Web.csproj -c Release -o ../../artifacts/demo-app-web&& dotnet publish -r debian.8-x64 ./src/DemoApp.Migrator/DemoApp.Migrator.csproj -c Release -o ../../artifacts/demo-app-db-migrator"
