version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    volumes:
      - .:/demo-app-web
    working_dir: /demo-app-web
    command: /bin/bash -c "dotnet restore ./DemoApp.sln && dotnet publish ./DemoApp.sln -c Release -r debian.8-x6 -o ./obj/Docker/publish"
