version: '3'

services:
  demo-app-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo-app-db

  demo-app-db-migrator:
    depends_on:
      - demo-app-db
    image: demo-app-db-migrator
    env_file:
      - ./docker-compose.env
    build:
      context: ./src/DemoApp.Migrator
      dockerfile: Dockerfile
      args:
        source: .

  demo-app-web:
    depends_on:
      - demo-app-db-migrator
    image: demo-app-web
    ports:
      - 8080:80
    env_file:
      - ./docker-compose.env
    build:
      context: ./src/DemoApp.Web
      dockerfile: Dockerfile
      args:
        source: .