apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  replicas: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: demo-app-web
        version: #{Build.BuildId}#
    spec:
      imagePullSecrets:
      - name: netdevday-secret
      containers:
      - name: demo-app-web
        # (!) Pulling the latest image is not a good idea.
        # - You never know which version is deployed, better to use concrete tags
        # - If you fail to change the imagePullPolicy to 'Always', the latest version will not be pulled
        image: netdevdaydemo.azurecr.io/demo-app-web:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /Home
            port: 80
            httpHeaders:
              - name: Content-Type
                value: application/json
          initialDelaySeconds: 10
          periodSeconds: 5
      - name: poc-kubectl-sidecar
        image: lachlanevenson/k8s-kubectl
        command:
        - kubectl
        - "proxy"
        - "--port=8000"
        ports:
        - containerPort: 8000