apiVersion: v1
kind: Service
metadata:
  name: poc-kubernetes-service-svc
  labels:
    app: poc-kubernetes-service
    kind: api
    accessibility: external
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30080
      protocol: TCP
  selector:
    app: poc-kubernetes-service
    accessibility: external